### ISSUE TITLE
Excelize used in go can't save files in docker container

### ISSUE THREAD

**Issue by arno-cma** [qax-os/excelize#1471]
We developed a quick prototype that uses Excelize that creates a clone of the original excel spreadsheet:
1.  to open a spreadsheet
2. save it as a duplicate
3. open the duplicate 
4. add data

This works without any issues locally, but we do need to run it inside a docker container (we're looking at alternatives as well)

**Steps to reproduce the issue:**

our code base is fairly simple and works in our development environment

`	// clone the excel file
	template, _ := excelize.OpenFile(excelTemplateURI)
	path := os.Getenv("KO_DATA_PATH") + "/"

	template.SaveAs(path + "MarketIndicators_" + dates[0] + ".xlsx")
	template.Close()`

we then use KO to build and deploy it a local docker deamon.

**Describe the results you received:**
However when running inside a docker container we get the following error:
`2023/02/15 15:05:20 http: panic serving 127.0.0.1:46926: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1850 +0xb8
panic({0x339400, 0x6e1970})
        runtime/panic.go:890 +0x260
github.com/xuri/excelize/v2.(*File).SaveAs(0x40003b2090?, {0x40003b20f0?, 0x242?}, {0x0?, 0x0?, 0x4000468090?})
        github.com/xuri/excelize/v2@v2.7.0/file.go:75 +0x34`

**Describe the results you expected:**
Ideally this would be a non-issue as in our development environment this process works.

**Output of `go version`:**

```text
go version go1.19.3 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.7.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OS Ventura 13.2 
Microsoft 365
code run in isolated docker container.

**Comment by arno-cma** [comment]
Sorry I realized a coding mistake 

`	template, _ := excelize.OpenFile(excelTemplateURI)
	path := os.Getenv("KO_DATA_PATH") + "/"`

should be 

`	
path := os.Getenv("KO_DATA_PATH") + "/"
template, _ := excelize.OpenFile(excelTemplateURI)
	`
