### ISSUE TITLE
GetConditionalFormats reads a conditional format that is higher than the average and reports a null pointer error

### ISSUE THREAD

**Issue by ShowerBandV** [qax-os/excelize#1745]
**Description**
I have an Excel file that sets a conditional format higher than the average, and calling GetConditionalFormats reports an error with a null pointer

here is my code
```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/xuri/excelize/v2"
)

func main() {
	file, err := excelize.OpenFile("ddd.xlsx")
	if err != nil {
		fmt.Printf("open file failed:%s", err.Error())
		return
	}
	formats, err := file.GetConditionalFormats("Sheet1")
	if err != nil {
		fmt.Printf("get conditionformats failed:%s", err.Error())
		return
	}
	fmt.Println(formats)
}
```
and the error is
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5407b0]

goroutine 1 [running]:
github.com/xuri/excelize/v2.extractCondFmtAboveAverage(_, _)
        D:/Users/yl5713/go/pkg/mod/github.com/xuri/excelize/v2@v2.8.0/styles.go:2701 +0x90 
github.com/xuri/excelize/v2.(*File).GetConditionalFormats(0xc00016e160, {0x5ef156, 0x6})   
        D:/Users/yl5713/go/pkg/mod/github.com/xuri/excelize/v2@v2.8.0/styles.go:2857 +0x6be
main.main()
        E:/projects/excelizeDemo/main.go:17 +0x1c5

```

After changing the conditional format to below average, GetConditionalFormats can be used normally. The conditional format is above average, and there is no AboveAverage in the XML. I hope excelize can handle it。
```xml
<conditionalFormatting sqref="A1:C8">
<cfRule type="aboveAverage" dxfId="2" priority="2"/>
</conditionalFormatting>
<conditionalFormatting sqref="F1:H8">
<cfRule type="aboveAverage" dxfId="0" priority="1" aboveAverage="0"/>
</conditionalFormatting>
```

**Comment by ShowerBandV** [comment]
github.com/xuri/excelize/v2 v2.8.0
